// Code generated by mockery v2.10.0. DO NOT EDIT.

package port

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockExplorerService is an autogenerated mock type for the ExplorerService type
type MockExplorerService struct {
	mock.Mock
}

// GetAssetCurrency provides a mock function with given fields: ctx, assetId
func (_m *MockExplorerService) GetAssetCurrency(ctx context.Context, assetId string) (string, error) {
	ret := _m.Called(ctx, assetId)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, assetId)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, assetId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
