// Code generated by mockery v2.10.0. DO NOT EDIT.

package port

import (
	context "context"
	"github.com/shopspring/decimal"

	mock "github.com/stretchr/testify/mock"
)

// MockRateService is an autogenerated mock type for the RateService type
type MockRateService struct {
	mock.Mock
}

// ConvertCurrency provides a mock function with given fields: ctx, source, target
func (_m *MockRateService) ConvertCurrency(ctx context.Context, source string, target string) (decimal.Decimal, error) {
	ret := _m.Called(ctx, source, target)

	var r0 decimal.Decimal
	if rf, ok := ret.Get(0).(func(context.Context, string, string) decimal.Decimal); ok {
		r0 = rf(ctx, source, target)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, source, target)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
