// Code generated by sqlc. DO NOT EDIT.

package queries

import (
	"database/sql"
)

type Market struct {
	MarketID     sql.NullInt32
	ProviderName string
	Url          string
	BaseAsset    string
	QuoteAsset   string
}
