// Code generated by sqlc. DO NOT EDIT.

package queries

import ()

type Market struct {
	MarketID     int32
	AccountIndex int32
	ProviderName string
	Url          string
	Credentials  string
	BaseAsset    string
	QuoteAsset   string
}
