// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package queries

import (
	"context"
)

const getAllMarkets = `-- name: GetAllMarkets :many
SELECT market_id, account_index, provider_name, url, credentials, base_asset, quote_asset FROM market
`

func (q *Queries) GetAllMarkets(ctx context.Context) ([]Market, error) {
	rows, err := q.db.QueryContext(ctx, getAllMarkets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Market
	for rows.Next() {
		var i Market
		if err := rows.Scan(
			&i.MarketID,
			&i.AccountIndex,
			&i.ProviderName,
			&i.Url,
			&i.Credentials,
			&i.BaseAsset,
			&i.QuoteAsset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMarket = `-- name: InsertMarket :one
INSERT INTO market (
    account_index, provider_name,url,credentials,base_asset,quote_asset) VALUES (
             $1, $2, $3, $4, $5, $6
    )
    RETURNING market_id, account_index, provider_name, url, credentials, base_asset, quote_asset
`

type InsertMarketParams struct {
	AccountIndex int32
	ProviderName string
	Url          string
	Credentials  string
	BaseAsset    string
	QuoteAsset   string
}

func (q *Queries) InsertMarket(ctx context.Context, arg InsertMarketParams) (Market, error) {
	row := q.db.QueryRowContext(ctx, insertMarket,
		arg.AccountIndex,
		arg.ProviderName,
		arg.Url,
		arg.Credentials,
		arg.BaseAsset,
		arg.QuoteAsset,
	)
	var i Market
	err := row.Scan(
		&i.MarketID,
		&i.AccountIndex,
		&i.ProviderName,
		&i.Url,
		&i.Credentials,
		&i.BaseAsset,
		&i.QuoteAsset,
	)
	return i, err
}
